#!/bin/bash
# TGH service control shell script

# PYTHON_BIN="/usr/local/bin/python2.7"
# SERVICE_BIN="/etc/tgh-tul-tools/src/main.py"
# CONFIG_FILE="/etc/tgh-tul-tools/config/config.json"
# LIMIT_USER="tgh-worker"

PYTHON_BIN="python"
SERVICE_BIN="/home/jan-hybs/Dokumenty/projects/tgh-tul-tools/src/main.py"
CONFIG_FILE="/home/jan-hybs/Dokumenty/projects/tgh-tul-tools/www/config/config-hybs.json"
LIMIT_USER="jan-hybs"

if [ $# -eq 0 ]
  then
    echo "No arguments supplied"
    echo "usage: tgh-service start|stop|restart|debug"
    exit 1
fi

if [ $# -eq 1 ]
  then
      # execute command
      action=$1
      cmd="${PYTHON_BIN} ${SERVICE_BIN} ${action} ${CONFIG_FILE}"

      echo "Running: '${cmd}' as '${LIMIT_USER}'"
      su - ${LIMIT_USER} -c "${cmd}"
fi

# run as root
if [ $# -eq 2 ]
  then
      # execute command
      LIMIT_USER=$2
      action=$1
      cmd="${PYTHON_BIN} ${SERVICE_BIN} ${action} ${CONFIG_FILE}"

      echo "Running: '${cmd}' as '${LIMIT_USER}'"
      su - ${LIMIT_USER} -c "${cmd}"
fi